name: vlnram
channels:
  - conda-forge
  - aihabitat
  - ostrokach-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - brotli-python=1.0.9=py38h6a678d5_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ipython=8.12.2=py38h06a4308_0
  - jedi=0.19.1=py38h06a4308_0
  - joblib=1.4.2=py38h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.29=ha39b09d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - line_profiler=4.1.1=py38hdb19cb5_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - msgpack-numpy=0.4.8=pyhd8ed1ab_0
  - msgpack-python=1.0.3=py38h43d8883_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.7.0=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - scipy=1.10.1=py38h32ae08f_1
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - traitlets=5.14.3=py38h06a4308_0
  - urllib3=2.2.3=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.0.1
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - compel==2.1.1
      - decorator==4.4.2
      - diffusers==0.20.1
      - easydict==1.9
      - filelock==3.16.1
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - gym==0.26.2
      - h5py==3.11.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.2
      - idna==3.10
      - ifcfg==0.24
      - importlib-metadata==8.5.0
      - jinja2==3.1.4
      - jsonlines==2.0.0
      - lmdb==1.6.2
      - markupsafe==2.1.5
      - moviepy==1.0.3
      - mpmath==1.3.0
      - networkx==2.5.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - openai-clip==1.0.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.2.0.32
      - packaging==25.0
      - pillow==10.4.0
      - protobuf==3.20.0
      - psutil==7.0.0
      - pyparsing==3.1.4
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - shapely==1.7.1
      - six==1.17.0
      - sympy==1.13.3
      - tb-nightly==2.20.0a20250708
      - tensorboardx==2.4.1
      - tokenizers==0.13.3
      - torch==2.4.1+cu121
      - torch-scatter==2.1.2+pt24cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - transformers==4.30.0
      - triton==3.0.0
      - typing-extensions==4.13.2
      - wcwidth==0.2.13
      - webdataset==0.1.40
      - yacs==0.1.8
      - zipp==3.20.2
prefix: /root/miniconda3/envs/vlnram
